version: '3.7'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: book-shop-backend
    links:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: book-shop-mongo
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: book-shop-redis
